""" Take a random sample of a DataBuilder file
    
"""

import sqlite3 as sq,argparse,random,shutil
parser = argparse.ArgumentParser()
parser.add_argument("dbin",help="SQLite input file generated by DataBuilder")
parser.add_argument("-o","--outfile",help="SQLite output file",default="")
parser.add_argument("-n","--nsamples",help="Number (if integer > 1) or fraction of samples to keep. If '1' (default) then keeps all samples",default=1,type=float)
parser.add_argument("-l","--log",help="Log verbose sql",action="store_true")
parser.add_argument("-f","--fromdate",help="From date, in YYYY-MM-DD format (default 0)",default='0')
parser.add_argument("-t","--todate",help="To date, in YYYY-MM-DD format (default 9999-01-01)",default='9999-01-01')
parser.add_argument("-s","--select",help="Additional SQL filtering conditions for observations to be appended to a 'WHERE' clause after an 'AND' keyword",default='1=1')
args = parser.parse_args()
dolog = args.log

def logged_execute(cnx, statement, comment=''):
    if dolog:
        if comment != '':
            print 'execute({0}): {1}'.format(comment, statement)
        else:
            print 'execute: {0}'.format(statement)
    return cnx.execute(statement)

def main(cnx,samples,fromdate,todate,sel):
  if int(samples) != samples or samples == 1:
    npt = logged_execute(cnx,"select count(*) from patient_dimension").fetchone()[0]
    samples = int(round(samples*npt))
  else: samples = int(samples)
    
  qry_pat = """create table patient_dimension_tmp as select * from patient_dimension 
	       where patient_num in 
	       (select patient_num from patient_dimension order by random() limit {0})"""
  qry_obs = """create table observation_fact_tmp as select * from observation_fact
	       where patient_num in (select patient_num from patient_dimension_tmp)
	       and start_date > '{0}' and start_date < '{1}' and {2}"""
  logged_execute(cnx,qry_pat.format(samples))
  logged_execute(cnx,qry_obs.format(fromdate,todate,sel))
  qry_delete = "delete from {0}"
  qry_insert = "insert into {0} select * from {0}_tmp"
  qry_drop = "drop table {0}_tmp"
  for ii in ['patient_dimension','observation_fact'] :
    logged_execute(cnx,qry_delete.format(ii))
    logged_execute(cnx,qry_insert.format(ii))
    logged_execute(cnx,qry_drop.format(ii))
  cnx.commit()
  logged_execute(cnx,'vacuum')

if __name__ == '__main__':
    outfile = args.outfile
    if outfile=="":
      outfile = "sample_"+args.dbin
    shutil.copyfile(args.dbin,outfile)
    con = sq.connect(outfile)
    main(con,args.nsamples,args.fromdate,args.todate,args.select)
